"""TicketType model yaratildi

Revision ID: 37db9b1dc2ff
Revises: 25459fd10829
Create Date: 2026-08-22 17:35:56.572169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37db9b1dc2ff'
down_revision: Union[str, Sequence[str], None] = '25459fd10829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_types',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity_total', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.String(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.String(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ticket_types_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_types'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_types')
    # ### end Alembic commands ###
