"""tickets table

Revision ID: 63c52002d57a
Revises: dfd1509da1ac
Create Date: 2026-08-29 20:41:15.819245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c52002d57a'
down_revision: Union[str, Sequence[str], None] = 'dfd1509da1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'USED', 'CANCELLED', name='ticketstatus'), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_by_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.String(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.String(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_tickets_event_id_events')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_tickets_order_id_orders')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_tickets_owner_user_id_users')),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], name=op.f('fk_tickets_ticket_type_id_ticket_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
