"""tickets table

Revision ID: 85f583715be1
Revises: 6a46a7f31c3d
Create Date: 2026-08-29 21:15:13.622453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85f583715be1'
down_revision: Union[str, Sequence[str], None] = '6a46a7f31c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('VALID', 'USED', 'CANCELLED', name='ticketstatus'),
               nullable=True)
    op.alter_column('tickets', 'checked_in_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'checked_in_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('VALID', 'USED', 'CANCELLED', name='ticketstatus'),
               nullable=False)
    # ### end Alembic commands ###
